# Generated by Django 3.2.13 on 2022-04-20 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_api', '0002_forecast'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forecast',
            old_name='created_on',
            new_name='requested_on',
        ),
        migrations.AddField(
            model_name='forecast',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='forecast_api.user'),
            preserve_default=False,
        ),
    ]
